version: '3.9'

services:
  postgres_db:
    container_name: dbt-postgres-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 3000:5432
    volumes:
      - postgres_db_storage:/var/lib/postgresql/data
  
  dbt_dwh:
    container_name: dbt-dwh-app
    build: .
    image: dbt-dwh-img
    command: dbt run

volumes:
  postgres_db_storage: